import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createInvestigation,investigations,health} from './services/api';
import './styles/app.css';
function App(){
 const [query,setQuery]=useState(''); const [model,setModel]=useState('nex-agi/nex-n2.5-mini:free'); const [items,setItems]=useState([]); const [active,setActive]=useState(null); const [busy,setBusy]=useState(false); const [api,setApi]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{health().then(()=>setApi(true)).catch(()=>setApi(false)); investigations().then(setItems).catch(()=>{});},[]);
 async function run(){if(!query.trim())return;setBusy(true);setError('');try{const x=await createInvestigation({query,model,max_results:20});setActive(x);setItems(await investigations());}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="app"><aside><div className="brand">ROBIN<span> / INTEL</span></div><nav><a className="active">Overview</a><a>Investigations</a><a>Threat Actors</a><a>Evidence</a><a>Relationship Graph</a></nav><div className="api">● API {api?'ONLINE':'OFFLINE'}</div></aside><main><header><div><div className="eyebrow">THREAT INTELLIGENCE PLATFORM</div><h1>Investigation Workspace</h1></div><div className="badge">Authorized OSINT</div></header><section className="hero"><div><h2>Start an investigation</h2><p>Search, collect, correlate and summarize intelligence from your configured sources.</p></div><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="Actor alias, identifier, keyword, IOC…"/><input className="model" value={model} onChange={e=>setModel(e.target.value)} placeholder="LLM model"/><button disabled={busy||!model.trim()} onClick={run}>{busy?'Running…':'Investigate'}</button></div>{error&&<div className="error">{error}</div>}</section><div className="stats"><div><small>INVESTIGATIONS</small><strong>{items.length}</strong></div><div><small>ACTIVE SOURCES</small><strong>{active?.results?.length||0}</strong></div><div><small>STATUS</small><strong>{busy?'RUNNING':'READY'}</strong></div></div>{active?<section className="panel"><div className="panelhead"><div><small>INVESTIGATION #{active.id}</small><h2>{active.query}</h2><p>Refined query: <b>{active.refined_query}</b></p></div><span className="status">{active.status}</span></div><div className="summary"><h3>Analyst Summary</h3><p>{active.summary||'No summary returned.'}</p></div><h3>Evidence Sources</h3><div className="sources">{active.results.map((r,i)=><article key={i}><div className="num">{String(i+1).padStart(2,'0')}</div><div><b>{r.title||'Untitled source'}</b><div className="link">{r.link||r.url||'No URL'}</div></div></article>)}</div></section>:<section className="panel"><h2>Recent investigations</h2>{items.length?<div className="recent">{items.map(x=><button key={x.id} onClick={()=>setActive(x)}><span>#{x.id}</span><b>{x.query}</b><small>{x.status}</small></button>)}</div>:<p className="muted">No investigations yet.</p>}</section>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
